/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ref: typeof import('vue')['ref']
  const showToast: typeof import('vant/es')['showToast']
}
